### ISSUE TITLE
testing-mocha-chai-auth doesn't work out of the box on Windows

### ISSUE THREAD

**Issue by IBwWG** [feathersjs/feathers-demos#22]
```dos
...ocha-chai-auth
> mocha test/ --recursive

module.js:472
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Kev\toptal\feathers-demos\examples\testing\t
esting-mocha-chai-auth\test\app.test.js:4:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Users\Kev\toptal\feathers-demos\examples\testing\testing-mocha-chai-au
th\node_modules\mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\Kev\toptal\feathers-demos\examples\testing\test
ing-mocha-chai-auth\node_modules\mocha\lib\mocha.js:219:14)
    at Mocha.run (C:\Users\Kev\toptal\feathers-demos\examples\testing\testing-mo
cha-chai-auth\node_modules\mocha\lib\mocha.js:487:10)
    at Object.<anonymous> (C:\Users\Kev\toptal\feathers-demos\examples\testing\t
esting-mocha-chai-auth\node_modules\mocha\bin\_mocha:459:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "mocha"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! test@0.0.0 mocha: `mocha test/ --recursive`
npm ERR! Exit status 1
```

Also, `node start` gives the same stack trace.

**Comment by IBwWG** [comment]
Sorry, my bad, nodejs is rusty with me, I forgot to `npm install`.
